name = "redirectorator"
main = "src/worker.js"
compatibility_date = "2024-01-01"

routes = [
    { pattern = "blocks.flashbots.net/*", zone_name = "flashbots.net" },
    { pattern = "explore.flashbots.net/*", zone_name = "flashbots.net" },
    { pattern = "suave.flashbots.net/*", zone_name = "flashbots.net" },
    { pattern = "suave-alpha.flashbots.net/*", zone_name = "flashbots.net" },
    { pattern = "transparency.flashbots.net/*", zone_name = "flashbots.net" },
    { pattern = "datasets.flashbots.net/*", zone_name = "flashbots.net" },
]

[observability.logs]
enabled = false

[vars]
DEBUG = "false"
DEFAULT_STATUS = 410
DEFAULT_REDIRECT_DELAY = 5
