name = "redirectorator"
main = "src/worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "blocks.flashbots.net/*", zone_name = "flashbots.net" }
]

[observability.logs]
enabled = false
